import type { Metadata } from "next";
import "./globals.css";
import NavbarComponent from "@/components/layout/navbar";
import FooterComponent from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased container mx-auto min-h-screen max-w-7xl p-4 flex flex-col`}
      >
        <NavbarComponent />
        <main className="flex-1">{children}</main>
        <FooterComponent />
      </body>
    </html>
  );
}
